hydra:
    run:
        dir: .


model_name: "vggsfm_v2_0_0"

seed: 0
img_size: 1024


debug: True


center_order: False
mixed_precision: fp16
extract_color: True
filter_invalid_frame: True

comple_nonvis: True
query_frame_num: 3
robust_refine: 5
BA_iters: 10

fine_tracking: True

camera_type: "SIMPLE_RADIAL"   # optional: ["SIMPLE_PINHOLE", "SIMPLE_RADIAL"]

load_gt: False
viz_visualize: False
gr_visualize: False

fmat_thres: 1.0
max_reproj_error: 1.0
init_max_reproj_error: 2.0
max_query_pts: 2048

dense_depth: True

avg_pose: True
shared_camera: True

save_to_disk: True
SCENE_DIR: showroom_filt/

resume_ckpt:  ckpt/vggsfm_v2_0_0.bin
auto_download_ckpt: True

query_method: "aliked"

use_poselib: True

shift_point2d_to_original_res: True

make_reproj_video: True

visual_tracks: False
visual_query_points: True
visual_dense_point_cloud: True

query_by_midpoint: False
query_by_interval: False

concat_extra_points: False
extra_pt_pixel_interval: -1
extra_by_neighbor: -1

MODEL:
    _target_: vggsfm.models.VGGSfM

    TRACK:
        _target_: vggsfm.models.TrackerPredictor

        efficient_corr: False

        COARSE:
            stride: 4
            down_ratio: 2
            FEATURENET:
                _target_: vggsfm.models.BasicEncoder

            PREDICTOR:
                _target_: vggsfm.models.BaseTrackerPredictor

        FINE:
            FEATURENET:
                _target_: vggsfm.models.ShallowEncoder


            PREDICTOR:
                _target_: vggsfm.models.BaseTrackerPredictor
                depth: 4
                corr_levels: 3
                corr_radius: 3
                latent_dim: 32
                hidden_size: 256
                fine: True
                use_spaceatt: False

    CAMERA:
        _target_: vggsfm.models.CameraPredictor


    TRIANGULAE:
        _target_: vggsfm.models.Triangulator    


